### ISSUE TITLE
Crash on start if WebAPI is unavailable.

### ISSUE THREAD

**Issue by agaertner** [Tharylia/GW2-MumbleMock#1]
Mock service should not require WebAPI to be available.

**If the API connection can be established:** Load values from it for selections.

**If the API is unavailable:** Simply have default values **and** allow manual input **instead of crashing**.

This way offline work and work in secure environments becomes possible.

Looks good so far.  👍

**Comment by Tharylia** [comment]
I knew I forgot something..
Will be fixed in next release

**Comment by Tharylia** [comment]
Fixed with release 0.1.2
